from langchain.prompts import PromptTemplate
from typing import Any
from ExpertRecSystem.agents.base import Agent
from ExpertRecSystem.utils import read_json


class Recommender(Agent):
    """
    The Recommender class extends the base Agent class to provide recommendations using a language model.
    It initializes the language model based on a configuration file and builds prompts for generating recommendations.
    """

    def __init__(self, config_path: str, *args, **kwargs) -> None:
        """
        Initialize the Recommender with the specified configuration file.

        Args:
            `config_path` (`str`): The path to the configuration file for initializing the recommender.
            `*args` (`Any`): Additional positional arguments for the base class.
            `**kwargs` (`Any`): Additional keyword arguments for the base class.
        """
        super().__init__(*args, **kwargs)
        config = read_json(config_path)
        self.recommender = self.get_LLM(config=config)
        self.json_mode = self.recommender.json_mode

    @property
    def recommender_prompt(self) -> PromptTemplate:
        """
        Property that returns the prompt template for the recommender.

        Returns:
            `PromptTemplate`: The prompt template for generating recommendations.
        """
        return self.prompts["recommender_prompt"]

    @property
    def recommender_example(self) -> str:
        """
        Property that returns an example prompt for the recommender.

        Returns:
            `str`: The example prompt if available; otherwise, an empty string.
        """
        if "recommender_example" in self.prompts:
            return self.prompts["recommender_example"]
        else:
            return ""

    def _build_recommender_prompt(self, **kwargs) -> str:
        """
        Build the recommender prompt by formatting the prompt template with provided project and expert information.

        Args:
            `project` (`str`): The name or description of the project.
            `experts` (`list`): A list of expert descriptions.

        Returns:
            `str`: The formatted prompt string ready for generating recommendations.
        """
        project = kwargs["project"]
        experts = kwargs["experts"]
        prompt = self.recommender_prompt.format(
            example=self.recommender_example,
            project=project,
        )
        for i, des in enumerate(experts, start=1):
            prompt += f"\n专家{i}:{des}\n"

        return prompt

    def forward(self, **kwargs: Any) -> Any:
        """
        Forward pass of the Recommender. Builds the recommender prompt and processes it with the language model.

        Args:
            `**kwargs` (`Any`): The keyword arguments needed to build the recommender prompt.

        Returns:
            `Any`: The response generated by the language model based on the built prompt.
        """
        prompt = self._build_recommender_prompt(**kwargs)
        response = self.recommender(prompt)
        return response
